apiVersion: apps/v1beta1
kind: Deployment
metadata:
    name: ddsserver
    namespace: cloud
spec:
    selector:
      matchLabels:
        app: ddsserver
        tier: backend
    minReadySeconds: 5
    strategy:
      type: RollingUpdate
      rollingUpdate:
        maxSurge: 50%
        maxUnavailable: 0
    replicas: 1
    template:
        metadata:
            annotations: {}
            labels:
                app: ddsserver
                tier: backend
        spec:
            terminationGracePeriodSeconds: 60
            containers:
                - name: ddsserver
                  image: docker.v2.aispeech.com/aispeech/ddsserver:{{ ddsserver_version }}
                  imagePullPolicy: IfNotPresent
                  readinessProbe:
                    httpGet:
                      path: /healthz
                      port: 28002
                    initialDelaySeconds: 10
                    periodSeconds: 30
                    timeoutSeconds: 10
                  livenessProbe:
                    httpGet:
                      path: /healthz
                      port: 28002
                    initialDelaySeconds: 10
                    periodSeconds: 30
                    timeoutSeconds: 10
                  lifecycle:
                    preStop:
                      exec:
                        command: ["/opt/aispeech/openresty/nginx/sbin/nginx", "-p", "/opt/aispeech", "-c", "/opt/aispeech/conf/nginx.conf", "-s", "quit"]                     
                  ports:
                    - containerPort: 28002
                  env:
                    - name: NODENAME
                      valueFrom:  
                        fieldRef:  
                          fieldPath: spec.nodeName                    
                  envFrom:
                    - configMapRef:
                        name: cloud-config
                  volumeMounts:
                    - name: ddsserver-data
                      mountPath: /opt/aispeech/resources/resserver
            volumes:
                - name: "ddsserver-data"
                  hostPath:
                    path: "/data/share/resserver"                        
            nodeSelector:
                ddsserver: "1"
---
apiVersion: v1
kind: Service
metadata:
    name: ddsserver
    namespace: cloud
spec:
    type: NodePort
    ports:
    - port: 28002
      name: http
      targetPort: 28002
    selector:
        app: ddsserver
        tier: backend
