apiVersion: apps/v1beta1
kind: Deployment
metadata:
    name: ssmserver
    namespace: cloud
spec:
    selector:
      matchLabels:
        app: ssmserver
        tier: backend
    minReadySeconds: 5
    strategy:
      type: RollingUpdate
      rollingUpdate:
        maxSurge: 50%
        maxUnavailable: 0
    replicas: 1
    template:
        metadata:
            annotations: {}
            labels:
                app: ssmserver
                tier: backend
        spec:
            terminationGracePeriodSeconds: 60
            containers:
                - name: ssmserver
                  image: docker.v2.aispeech.com/aispeech/ssmserver:{{ ssmsserver_version }}
                  imagePullPolicy: IfNotPresent
                  readinessProbe:
                    httpGet:
                      path: /healthz
                      port: 28002
                    initialDelaySeconds: 10
                    periodSeconds: 30
                    timeoutSeconds: 10
                  livenessProbe:
                    httpGet:
                      path: /healthz
                      port: 28002
                    initialDelaySeconds: 10
                    periodSeconds: 30
                    timeoutSeconds: 10
                  lifecycle:
                    preStop:
                      exec:
                        command: ["/opt/aispeech/openresty/nginx/sbin/nginx", "-p", "/opt/aispeech", "-c", "/opt/aispeech/conf/nginx.conf", "-s", "quit"]                  
                  ports:
                    - containerPort: 28002
                  envFrom:
                    - configMapRef:
                        name: cloud-config
            nodeSelector:
                ssmserver: "1"
---
apiVersion: v1
kind: Service
metadata:
    name: ssmserver
    namespace: cloud
spec:
    ports:
    - port: 28002
      targetPort: 28002
    selector:
        app: ssmserver
        tier: backend
