apiVersion: kubeadm.k8s.io/v1alpha1
kind: MasterConfiguration
kubernetesVersion: v1.6.1
networking:
  podSubnet: 10.244.0.0/16
etcd:
  endpoints:
  - http://{{ master1_ip }}:2379
  - http://{{ master2_ip }}:2379
  - http://{{ master3_ip }}:2379
